### ISSUE TITLE
Export to static image without orca

### ISSUE THREAD

**Issue by ChA0S-f4me** [SciProgCentre/plotly.kt#86]
How can I export plot to local PNG or JPG **without** orca?

**Comment by altavir** [comment]
Since Plotly is a web-based library, it is not possible to directly export image from JVM. It is possible to do from the plot itself:
![image](https://user-images.githubusercontent.com/9514268/170242256-90ca707c-329c-42e1-a13e-21514f0847d3.png)
You can change the format of exported image like it is done [here](https://github.com/mipt-npm/plotly.kt/blob/77c3882daff7e65b51e4ef6761a7147c01c3ee9c/examples/src/main/kotlin/downloadChartAsSVG.kt#L11-L15).

It is also possible to export image via python package provided by plotly, but it is not that relyable: https://github.com/mipt-npm/plotly.kt/blob/master/examples/src/main/kotlin/svgSaveViaOrca.kt

**Comment by ChA0S-f4me** [comment]
> Since Plotly is a web-based library, it is not possible to directly export image from JVM. It is possible to do from the plot itself: ![image](https://user-images.githubusercontent.com/9514268/170242256-90ca707c-329c-42e1-a13e-21514f0847d3.png) You can change the format of exported image like it is done [here](https://github.com/mipt-npm/plotly.kt/blob/77c3882daff7e65b51e4ef6761a7147c01c3ee9c/examples/src/main/kotlin/downloadChartAsSVG.kt#L11-L15).
> 
> It is also possible to export image via python package provided by plotly, but it is not that relyable: https://github.com/mipt-npm/plotly.kt/blob/master/examples/src/main/kotlin/svgSaveViaOrca.kt

I need to export it to PNG from code, not manually

**Comment by altavir** [comment]
Sadly, it is possible only via Orca. Plotly recommends to use the new tool Kaleido (https://plotly.com/python/static-image-export/), but last time we tried, it was bugged and was almost impossible to use outside python. As far as I can understan, it just uses chromium embedded to render the plot and save the picture. So this option does not work that well. Sadly, it is a limitation of the underlying library.
